let autoGeneratedOrderId = 1;
$('#txtOrderID').val('O-00' + autoGeneratedOrderId);

/** load all items to table */
function loadAllOderDetails() {

    /** removing table row repeating issue */
    $("#orderTblBody").empty();

    for (let oDetails of orderDetails) {
        let orderRow = `<tr>
                        <td>${oDetails.iCode}</td>
                        <td>${oDetails.itemName}</td>
                        <td>${oDetails.price}</td>
                        <td>${oDetails.Qty}</td>
                        <td>${oDetails.total}</td>
                   </tr>`;
        $('#orderTblBody').append(orderRow);
        bool = false;
    }

}

function loadAllCustomersToCombo() {
    $('#orderCustomerID').empty();
    for (let customer of customerDetails) {
        $("#orderCustomerID").append(`<option>${customer.id}</option>`)
    }
}

/** combo operation on oder id */
$('#orderCustomerID').on('click', function () {
    let customerID = $('#orderCustomerID').val();
    for (let i = 0; i < customerDetails.length; i++) {
        if (customerDetails[i].id === customerID) {
            $("#selectCusName").val(customerDetails[i].name);
            $("#orderCustomerContact").val(customerDetails[i].address);
            $("#orderCustomerAddress").val(customerDetails[i].contact);
        }
    }
})

function loadAllItemToCombo() {
    $('#itemCodeCombo').empty();
    for (let item of itemDetails) {
        $("#itemCodeCombo").append(`<option>${item.itemCode}</option>`)
    }
}

/** combo operation on oder id */
$('#itemCodeCombo').on('click', function () {
    let itemID = $('#itemCodeCombo').val();
    for (let i = 0; i < itemDetails.length; i++) {
        if (itemDetails[i].itemCode === itemID) {
            $("#selectItemCode").val(itemDetails[i].itemCode);
            $("#txtItemDescription").val(itemDetails[i].itemName);
            $("#txtItemPrice").val(itemDetails[i].unitPrice);
            $("#txtQTYOnHand").val(itemDetails[i].qty);
        }
    }
})

let bool = false;
let orderAmount = 0;

/** add to cart option */
$('#btnAddToTable').on('click', function () {
    $("#orderTblBody").empty();
    loadAllOderDetails();

    let a = $("#txtItemPrice").val()
    let b = $('#txtQty').val()

    let tot = a * b;

    let orderArray = new Order(
        $("#selectItemCode").val(),
        $("#txtItemDescription").val(),
        $("#txtItemPrice").val(),
        $("#txtQty").val(),
        tot,
        $('#txtOrderID').val()
    );

    let qty1;
    let qty2;
    let tot1;
    let tot2;

    for (let i = 0; i < orderDetails.length; i++) {
        let test = orderDetails[i];

        if ($('#selectItemCode').val() === test.iCode && $('#txtOrderID').val() === test.orderId) {

            bool = true;
            qty1 = parseInt(test.Qty);
            tot1 = parseInt(test.total);
            qty2 = parseInt($("#txtQty").val());
            tot2 = tot;

            // tot2 = parseInt(tot);

            test.iCode = $("#selectItemCode").val();
            test.itemName = $("#txtItemDescription").val();
            test.price = $("#txtItemPrice").val();
            test.Qty = (qty1 + qty2);
            test.total = (tot1 + tot2);

            $('#orderTblBody').empty();
        }
    }
    if (bool === false) {
        orderDetails.push(orderArray);
    }

    /** item quantity management */
    for (let i = 0; i < itemDetails.length; i++) {
        if (itemDetails[i].itemCode === $("#selectItemCode").val()) {
            itemDetails[i].qty = (itemDetails[i].qty) - ($("#txtQty").val());
        }
    }

    loadAllItem();
    loadAllOderDetails();

    $('#total').val()


    let x = $("#txtItemPrice").val()
    let y = $('#txtQty').val()

    let z = x * y;

    let singleOrder = new OrderDetails(
        $('#txtOrderID').val(),
        $('#txtDate').val(),
        $("#orderCustomerID").val(),
        $("#selectItemCode").val(),
        $("#txtQty").val(),
        z,
        $("#txtDiscount").val()
    );

    purchaseDetails.push(singleOrder);
    orderAmount += tot;
    loadAllPurchaseDetails();

});

let fullTot = 0;
let fullAmount = 0;

/** purchase order */
$('#btnSubmitOrder').on('click', function () {

    let x = $("#txtItemPrice").val()
    let y = $('#txtQty').val()

    let z = x * y;


    let singleOrder = {
        oID: $('#txtOrderID').val(),
        date: $('#txtDate').val(),
        cID: $("#orderCustomerID").val(),
        iCode: $("#selectItemCode").val(),
        oQty: $("#txtQty").val(),
        Tot: z,
        discount: $("#txtDiscount").val()
    }

    purchaseDetails.push(singleOrder);

    clear('#selectItemCode,#txtItemDescription,#txtItemPrice,#txtQTYOnHand');
    clear('#orderCustomerID,#selectCusName,#orderCustomerContact,#orderCustomerAddress');

    $('#txtOrderID').val('O-00' + autoGeneratedOrderId);
    autoGeneratedOrderId++;

    /** calculate total amount */
    for (let i = 0; i < orderDetails.length; i++) {
        let totVal = orderDetails[i];
        fullTot += parseInt(totVal.total)
    }
    let disCount = parseInt($('#txtDiscount').val());// 10%

    let discountedPrice = ((orderAmount / 100) * disCount);//50
    // $('#total').val("Rs/= " + fullTot);

    let oAmount = parseInt(orderAmount);


    $('#total').val("Rs/= " + (oAmount - discountedPrice));

    let customCash = parseInt($('#txtCash').val());//1000

    let subTotal = ((orderAmount / 100) * disCount);//500 - 50
    $('#subtotal').val(subTotal) // 450

    let s = customCash;//1000

    let d = discountedPrice;

    let sbTot;

    /** discount label management */
    if (discountedPrice > 0) {
        sbTot = subTotal;
        $('#subtotal').val(sbTot);
    } else {
        $('#subtotal').val("No discount");
    }

    let dc = s - d;

    $('#txtBalance').val(s - (oAmount - discountedPrice));


    orderDetails.splice(0, orderDetails.length)
    loadAllOderDetails();

    $('#txtOrderID').val('O-00' + autoGeneratedOrderId);
    autoGeneratedOrderId++;

    orderAmount = 0;

});
//

function deleteObj(textField, arrayRefNameForDelete) {

    let SearchResult = search($(textField).val(), arrayRefNameForDelete)
    if (SearchResult != null) {

        let indexOfItem = arrayRefNameForDelete.indexOf(SearchResult);
        arrayRefNameForDelete.splice(indexOfItem, 1);

        loadAllOderDetails();
        return true;
    } else {
        return false;
    }
}

$('#removeFromCart').on('click', function () {
    //TODO this is search field id -  searchToRemoveFromCart
    alert($('#searchToRemoveFromCart').val());
    deleteObj('#searchToRemoveFromCart', orderDetails);
    loadAllOderDetails();
});

/* option for button clear */
$('#btnClear').on('click', function () {
    clear('#txtQty,#subtotal,#total');
    clear('#txtCash,#txtDiscount,#txtBalance');
});

